CREATE TABLE IF NOT EXISTS QOJ_problem(
p_id INT NOT NULL AUTO_INCREMENT,
p_name VARCHAR(40) NOT NULL,
p_content VARCHAR(500) NULL,
p_answer VARCHAR(1000) NOT NULL,
p_table_name VARCHAR(300) NOT NULL,
p_date DATETIME NOT NULL DEFAULT NOW(),
pg_id INT NOT NULL,
FOREIGN KEY(pg_id) REFERENCES QOJ_problem_group(pg_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(p_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;