CREATE TABLE IF NOT EXISTS QOJ_user_problem(
up_id INT NOT NULL AUTO_INCREMENT,
up_state INT NOT NULL DEFAULT 0,
up_query VARCHAR(1000) NULL DEFAULT NULL,
up_date DATETIME NULL DEFAULT NULL,
user_id VARCHAR(20) NOT NULL,
p_id INT NOT NULL,
FOREIGN KEY(user_id) REFERENCES QOJ_user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(p_id) REFERENCES QOJ_problem(p_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(up_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;