CREATE TABLE IF NOT EXISTS QOJ_user(
user_id VARCHAR(20) NOT NULL,
user_pw VARCHAR(100) NOT NULL,
user_email VARCHAR(45) NOT NULL,
user_name VARCHAR(20) NOT NULL,
user_type INT NOT NULL DEFAULT 4,
user_date DATETIME NOT NULL DEFAULT NOW(),
class_id INT NULL DEFAULT NULL,
FOREIGN KEY(class_id) REFERENCES QOJ_class(class_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;