CREATE TABLE IF NOT EXISTS QOJ_manage_testDB(
mt_id INT NOT NULL AUTO_INCREMENT,
mt_table_name VARCHAR(100) NOT NULL,
mt_date DATETIME NOT NULL DEFAULT NOW(),
class_id INT NOT NULL,
FOREIGN KEY(class_id) REFERENCES QOJ_class(class_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(mt_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;