CREATE TABLE IF NOT EXISTS QOJ_manage_testDB(
mt_id INT NOT NULL AUTO_INCREMENT,
mt_table_name VARCHAR(100) NOT NULL,
mt_date DATETIME NOT NULL DEFAULT NOW(),
user_id VARCHAR(20) NOT NULL,
FOREIGN KEY(user_id) REFERENCES QOJ_user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(mt_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;