CREATE TABLE IF NOT EXISTS QOJ_user_class(
uc_id INT NOT NULL AUTO_INCREMENT,
user_id VARCHAR(20) NOT NULL,
class_id INT NOT NULL,
FOREIGN KEY(user_id) REFERENCES QOJ_user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(class_id) REFERENCES QOJ_class(class_id) ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(uc_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;