CREATE TABLE IF NOT EXISTS QOJ_class(
class_id INT NOT NULL AUTO_INCREMENT,
class_name VARCHAR(60) NOT NULL,
class_date DATETIME NOT NULL DEFAULT NOW(),
PRIMARY KEY(class_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;