CREATE TABLE IF NOT EXISTS QOJ_user(
user_id VARCHAR(20) NOT NULL,
user_pw VARCHAR(100) NOT NULL,
user_email VARCHAR(45) NOT NULL,
user_name VARCHAR(20) NOT NULL,
user_date DATETIME NOT NULL DEFAULT NOW(),
PRIMARY KEY(user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;